version: '3.9'
services:
  app:
    build:
      context: "./"
      target: "base"
    command: sh -c "npm install && npm start"
    environment:
        - NODE_ENV=development
        - PORT=3000
    ports:
        - "3000:3000"
    working_dir: /app
    volumes:
        - .:/app