import { createStoredZip } from '../../utils';
import { Site } from './site';

/**
 * Format a float for SIMPSON output.
 * If precision is specified, formats to fixed decimal places.
 * Otherwise prints clean representation ensuring decimal point for whole numbers.
 */
function formatFloat(val, precision = null) {
    const num = Number(val);
    if (!Number.isFinite(num)) return '0.0';

    if (precision !== null && precision !== undefined) {
        return num.toFixed(precision);
    }

    if (Number.isInteger(num)) {
        return `${num}.0`;
    }

    // Clean up float representation (e.g. 89.99999999999999 -> 90.0)
    const rounded = Number(num.toPrecision(12));
    if (Number.isInteger(rounded)) {
        return `${rounded}.0`;
    }
    return rounded.toString();
}

/**
 * Generate a minimal runnable SIMPSON .in script comment header.
 */
function generateHeader(filename = 'system.spinsys') {
    return [
        '# ==============================================================================',
        '# SIMPSON spin system generated by MagresView 2',
        '#',
        '# Minimal runnable SIMPSON .in template to source and simulate this system:',
        '#',
        `#   source ${filename}`,
        '#',
        '#   par {',
        '#       proton_frequency 400e6',
        '#       start_operator   I1x',
        '#       detect_operator  I1p',
        '#       np               8192',
        '#       sw               500000',
        '#       crystal_file     rep64',
        '#       verbose          0',
        '#   }',
        '#   proc pulseq {} {',
        '#       global par',
        '#       delay [expr 1e6/$par(sw)]',
        '#       store 1',
        '#       acq $par(np) 1',
        '#   }',
        '#   proc main {} {',
        '#       global par',
        '#       set f [fsimpson]',
        '#       fft $f',
        '#       fsave $f spectrum.dat -xreim',
        '#   }',
        '# ==============================================================================',
        '',
    ].join('\n');
}

/**
 * Convert a SpinSystem to a SIMPSON .spinsys format string.
 *
 * @param  {SpinSystem} sys     The SpinSystem model
 * @param  {object}     options Formatting and inclusion options
 * @return {string}             SIMPSON spinsys block
 */
export function toSimpson(sys, options = {}) {
    if (!sys.canExport) {
        const missing = sys.missingReferences.join(', ');
        throw new Error(`Cannot export spin system: missing shielding reference for element(s): ${missing}`);
    }

    const {
        observed_nucleus = null,
        q_order = 2,
        include_ms = true,
        include_efg = true,
        include_dip = true,
        include_j = true,
        include_angles = true,
        include_ms_angles = null,
        include_efg_angles = null,
        include_dipolar_angles = null,
        include_jcoupling_angles = null,
        include_cross_terms = true,
        ms_isotropic = false,
        precision = null,
        include_header = true,
        filename = 'system.spinsys',
    } = options;

    const useMsAngles = include_ms_angles !== null ? include_ms_angles : include_angles;
    const useEfgAngles = include_efg_angles !== null ? include_efg_angles : include_angles;
    const useDipAngles = include_dipolar_angles !== null ? include_dipolar_angles : include_angles;
    const useJAngles = include_jcoupling_angles !== null ? include_jcoupling_angles : include_angles;

    const nuclei = sys.sites.map(s => s.isotope);
    const uniqueNuclei = Array.from(new Set(nuclei)).sort();

    let channels;
    if (observed_nucleus) {
        if (!nuclei.includes(observed_nucleus)) {
            throw new Error(`Observed nucleus ${observed_nucleus} not found in the list of nuclei`);
        }
        channels = [observed_nucleus, ...uniqueNuclei.filter(iso => iso !== observed_nucleus)];
    } else {
        channels = uniqueNuclei;
    }

    const lines = [];
    if (include_header) {
        lines.push(generateHeader(filename));
    }

    lines.push('spinsys {');
    lines.push(`channels ${channels.join(' ')}`);
    lines.push(`nuclei ${nuclei.join(' ')}`);

    // 1. Shift lines
    if (include_ms) {
        for (const site of sys.sites) {
            if (!site.ms) continue;
            const idx = site.index + 1;
            const iso = site.shift_iso;
            const aniso = ms_isotropic ? 0 : site.shift_reduced_anisotropy;
            const asymm = ms_isotropic ? 0 : site.shift_asymmetry;

            let angles = [0.0, 0.0, 0.0];
            if (useMsAngles && !ms_isotropic) {
                angles = site.msEuler({ passive: true, degrees: true });
            }

            lines.push(
                `shift ${idx} ${formatFloat(iso, precision)}p ${formatFloat(aniso, precision)}p ${formatFloat(asymm, precision)} ` +
                `${formatFloat(angles[0], precision)} ${formatFloat(angles[1], precision)} ${formatFloat(angles[2], precision)}`
            );
        }
    }

    // 2. Quadrupole lines
    if (include_efg) {
        for (const site of sys.sites) {
            if (!site.efg || !site.isQuadrupoleActive || q_order <= 0) continue;
            const idx = site.index + 1;
            const Cq = site.Cq;
            const eta = site.efg_asymmetry;

            let angles = [0.0, 0.0, 0.0];
            if (useEfgAngles) {
                angles = site.efgEuler({ passive: true, degrees: true });
            }

            lines.push(
                `quadrupole ${idx} ${q_order} ${formatFloat(Cq, precision)} ${formatFloat(eta, precision)} ` +
                `${formatFloat(angles[0], precision)} ${formatFloat(angles[1], precision)} ${formatFloat(angles[2], precision)}`
            );
        }
    }

    // 3. Dipolar lines
    if (include_dip) {
        for (const c of sys.couplings) {
            if (c.type !== 'D') continue;
            const idx1 = c.site_i + 1;
            const idx2 = c.site_j + 1;
            const d = c.coupling_constant;

            let angles = [0.0, 0.0, 0.0];
            if (useDipAngles) {
                angles = c.euler({ passive: true, degrees: true });
            }

            lines.push(
                `dipole ${idx1} ${idx2} ${formatFloat(d, precision)} ` +
                `${formatFloat(angles[0], precision)} ${formatFloat(angles[1], precision)} ${formatFloat(angles[2], precision)}`
            );
        }
    }

    // 4. J-coupling lines
    if (include_j) {
        for (const c of sys.couplings) {
            if (c.type !== 'J') continue;
            const idx1 = c.site_i + 1;
            const idx2 = c.site_j + 1;
            const jIso = c.coupling_constant;
            // SIMPSON expects zeta / 2
            const jAniso = c.anisotropy / 2.0;
            const jAsymm = c.asymmetry;

            let angles = [0.0, 0.0, 0.0];
            if (useJAngles) {
                angles = c.euler({ passive: true, degrees: true });
            }

            lines.push(
                `jcoupling ${idx1} ${idx2} ${formatFloat(jIso, precision)} ${formatFloat(jAniso, precision)} ${formatFloat(jAsymm, precision)} ` +
                `${formatFloat(angles[0], precision)} ${formatFloat(angles[1], precision)} ${formatFloat(angles[2], precision)}`
            );
        }
    }

    // 5. Cross-terms
    if (include_cross_terms) {
        const siteHasQuadrupole = s => s.efg !== null && s.isQuadrupoleActive && q_order > 0;

        if (include_dip) {
            for (const c of sys.couplings) {
                if (c.type !== 'D') continue;
                const s1 = sys.sites[c.site_i];
                const s2 = sys.sites[c.site_j];
                if (siteHasQuadrupole(s1)) {
                    lines.push(`quadrupole_x_dipole ${c.site_i + 1} ${c.site_j + 1}`);
                }
                if (siteHasQuadrupole(s2)) {
                    lines.push(`quadrupole_x_dipole ${c.site_j + 1} ${c.site_i + 1}`);
                }
            }
        }

        for (const s of sys.sites) {
            if (siteHasQuadrupole(s) && s.ms !== null) {
                lines.push(`quadrupole_x_shift ${s.index + 1}`);
            }
        }
    }

    lines.push('}');
    lines.push('');

    return lines.join('\n');
}

/**
 * Split export: generate a ZIP file containing one .spinsys file per site.
 *
 * @param  {SpinSystem} sys      The SpinSystem model
 * @param  {string}     modelName Name of the model (for filename prefixes)
 * @param  {object}     options  SIMPSON writer options
 * @return {Uint8Array}          Stored ZIP binary data
 */
export function toSimpsonSplitZip(sys, modelName = 'model', options = {}) {
    if (!sys.canExport) {
        const missing = sys.missingReferences.join(', ');
        throw new Error(`Cannot export spin system: missing shielding reference for element(s): ${missing}`);
    }

    const zipFiles = {};

    for (let i = 0; i < sys.sites.length; i++) {
        const origSite = sys.sites[i];
        // Create isolated 1-site spin system
        const isolatedSite = new Site({
            ...origSite,
            index: 0,
        });

        const singleSys = {
            sites: [isolatedSite],
            couplings: [],
            warnings: [],
            missingReferences: [],
            canExport: true,
        };

        const safeLabel = origSite.label.replace(/[^a-zA-Z0-9_-]/g, '_');
        const filename = `${modelName}_${safeLabel}.spinsys`;
        const content = toSimpson(singleSys, {
            ...options,
            filename,
            include_dip: false,
            include_j: false,
            include_cross_terms: false,
        });

        zipFiles[filename] = content;
    }

    return createStoredZip(zipFiles);
}
