import { describe, it, expect } from 'vitest';
import { TensorData } from '@ccp-nc/crystvis-js';
import { Site } from './site';
import { Coupling } from './coupling';
import { SpinSystem } from './spinSystem';
import { generateReportTable } from './tables';

describe('Report tables generation', () => {
    const ms1 = new TensorData([[100, 0, 0], [0, 100, 0], [0, 0, -200]]);
    const ms2 = new TensorData([[200, 0, 0], [0, 100, 0], [0, 0, -300]]);

    const efg1 = new TensorData([[-0.25, 0, 0], [0, -0.25, 0], [0, 0, 0.5]]);

    const site1 = new Site({
        index: 0,
        isotope: '13C',
        element: 'C',
        label: 'C1',
        position: [0, 0, 0],
        ms: ms1,
        efg: null,
        reference: 180.0,
    });

    const site2 = new Site({
        index: 1,
        isotope: '2H',
        element: 'H',
        label: 'H1',
        position: [1.0, 2.0, 3.0],
        spin: 1.0,
        Q: 2.86,
        ms: ms2,
        efg: efg1,
        reference: 30.0,
    });

    const disp = [1.0, 2.0, 3.0];
    const dist = Math.hypot(...disp);
    const D_mat = [[-1000, 0, 0], [0, -1000, 0], [0, 0, 2000]];
    const dip = new Coupling({
        type: 'D',
        site_i: 0,
        site_j: 1,
        site_i_label: 'C1',
        site_j_label: 'H1',
        distance: dist,
        displacement: disp,
        tensor: new TensorData(D_mat),
        coupling_constant: 1000.0,
        anisotropy: 3000.0,
        asymmetry: 0,
    });

    const J_mat = [[100, 0, 0], [0, 100, 0], [0, 0, 100]];
    const jcoup = new Coupling({
        type: 'J',
        site_i: 0,
        site_j: 1,
        site_i_label: 'C1',
        site_j_label: 'H1',
        distance: dist,
        displacement: disp,
        tensor: new TensorData(J_mat),
        coupling_constant: 100.0,
        anisotropy: 0,
        asymmetry: 0,
    });

    const sys = new SpinSystem({
        sites: [site1, site2],
        couplings: [dip, jcoup],
    });

    it('generates MS table with shift, span, and skew', () => {
        const csv = generateReportTable(sys, 'ms', { format: 'csv', includeEuler: true });
        const lines = csv.trim().split('\n');
        expect(lines[0]).toBe('# MS Table generated by MagresView 2');
        expect(lines[1]).toContain('# Euler angles convention');
        expect(lines[2]).toContain('Label,Isotope,No. in label,s_iso/ppm,d_iso/ppm,Anisotropy/ppm,Red. aniso/ppm,Asymmetry,Span/ppm,Skew,alpha/deg,beta/deg,gamma/deg');

        // Site 1 row
        expect(lines[3]).toContain('C1,13C,1');
        // d_iso for site 1: ref (180) - iso (0) = 180
        expect(lines[3]).toContain('180');
    });

    it('generates EFG table with V_zz, C_q, and Euler angles', () => {
        const csv = generateReportTable(sys, 'efg', { format: 'csv', includeEuler: true });
        const lines = csv.trim().split('\n');
        expect(lines[0]).toBe('# EFG Table generated by MagresView 2');
        expect(lines[2]).toContain('Label,Isotope,No. in label,V_zz/au,Anisotropy/au,Asymmetry,C_q/MHz');

        // Only site 2 has EFG
        expect(lines.length).toBe(4);
        expect(lines[3]).toContain('H1,2H,2');
        // Vzz = 0.5, Cq = 234964.78 * 2.86 * 0.5 / 1e6 ≈ 0.336 MHz
        expect(lines[3]).toContain('0.50000');
    });

    it('generates Dipolar table with displacement vector in Angstroms (defect #6) and Euler angles (defect #7)', () => {
        const csv = generateReportTable(sys, 'dip', { format: 'csv', includeEuler: true });
        const lines = csv.trim().split('\n');
        expect(lines[0]).toBe('# Dipolar coupling table generated by MagresView 2');
        expect(lines[2]).toContain('Label 1,Isotope 1,Index 1,Label 2,Isotope 2,Index 2,Distance/Ang,r_x/Ang,r_y/Ang,r_z/Ang,D/kHz,Anisotropy/kHz,Asymmetry,alpha/deg,beta/deg,gamma/deg');

        const row = lines[3];
        // Index 1 = 1, Index 2 = 2 (not slice-local 0, defect #1 fixed)
        expect(row).toContain('C1,13C,1,H1,2H,2');
        // Displacement [1, 2, 3] (actual displacement in Ang, not unit vector!)
        expect(row).toContain('1,2,3');
        // D in kHz (1000 Hz / 1000 = 1.0 kHz -> 1)
        expect(row).toContain('1,3,0');
    });

    it('generates J table with anisotropy, asymmetry, and Euler angles (defect #7)', () => {
        const csv = generateReportTable(sys, 'isc', { format: 'csv', includeEuler: true });
        const lines = csv.trim().split('\n');
        expect(lines[0]).toBe('# J coupling table generated by MagresView 2');
        expect(lines[2]).toContain('Label 1,Isotope 1,Index 1,Label 2,Isotope 2,Index 2,J_iso/Hz,Anisotropy/Hz,Asymmetry,alpha/deg,beta/deg,gamma/deg');

        const row = lines[3];
        expect(row).toContain('C1,13C,1,H1,2H,2');
        expect(row).toContain('100,0,0');
    });

    it('escapes fields with commas using RFC 4180 in CSV', () => {
        const groupedSite = new Site({
            index: 0,
            isotope: '1H',
            element: 'H',
            label: 'H1,H2,H3',
            ms: ms1,
        });
        const gSys = new SpinSystem({ sites: [groupedSite] });
        const csv = generateReportTable(gSys, 'ms', { format: 'csv' });
        expect(csv).toContain('"H1,H2,H3"');
    });
});
